language: scala

sudo: false

scala:
   - 2.10.6
   - 2.11.11
   - 2.12.2

jdk:
  - oraclejdk8

script:
  - sbt ++${TRAVIS_SCALA_VERSION} "project $TEST_PROJECT" compile test:compile test

env:
  matrix:
  - TEST_PROJECT="dogJVM"
  - TEST_PROJECT="dogJS"

cache:
  directories:
    - $HOME/.ivy2/cache
